# Generated by Django 4.2.7 on 2026-01-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
    ]
